Bump default to PHP8.2
sumocoders/application-skeleton pull request #97
Opened 2023-04-27 09:12 UTC by dreadnip

2023-04-27 12:39 UTC, jonasdekeukelaere commented
Will need to be changed in gitlab-ci files as well

2023-04-27 12:39 UTC, jonasdekeukelaere requested changes
Will need to be changed in gitlab-ci files as well

2023-04-27 12:41 UTC, dreadnip commented
Good catch!

2023-04-28 08:30 UTC, jonasdekeukelaere approved these changes

2023-04-28 08:31 UTC, merged